services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_flask_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    networks:
      - app-network
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    # Healthcheck to ensure PostgreSQL is ready before app starts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 20s
      retries: 10

  app:
    build: .
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_DATABASE=todoapp_db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "5010:5000"

volumes:
  postgres_flask_data:

networks:
  app-network:
